### ISSUE TITLE
Release as Free and Open Source Software?

### ISSUE THREAD

**Issue by ijgnd** [jixiuf/my_autohotkey_scripts#1]
First of all: Thanks for sharing your ahk scripts. They have helped me a lot.

I want to share the AHK files I use on github and in a forum and they include your `emacs-key-sequence.ahk`. My problem: I don't find a license in your repo. So your software is proprietary software that in theory I may not share with other people outside of github. The fact that you shared on github doesn't give anyone permission for sharing. At the moment I need to include instructions for other people on how to download the file for themselves. But people who are not tech-savvy will fail. 

Would it be ok if I share this file under a GPLv2+ license (with proper attribution)? Even better: Would you add a free and open source license to the repo? This would help other people, too. There are many different open source licenses depending on your preferences, see e.g. https://choosealicense.com. I think it would be great if you added a BSD, MIT, MPLv2 or GPL2+ license. 

I hope that you don't consider this request as impertinent. I only ask because you prominently invite people to download your code [here](http://jixiuf.github.io/my_autohotkey_scripts/). 

Thanks for your time and once more thanks for sharing your great work.

**Comment by jixiuf** [comment]
I add a  GPLv2+ license
  80e473f
and any pull request are  welcome

**Comment by ijgnd** [comment]
That's awesome. Once more: Thank you so much! When I have something of general interest I'll make sure send a pull request.
